trigger:
  branches:
    include:
      - stage

pool:
  vmImage: ubuntu-latest

steps:
  - task: vercel-deployment-task@1
    name: Deploy
    inputs:
      vercelProjectId: "prj_muveo9etEU2iVv3PpDo92jvP5VV0"
      vercelOrgId: "team_AUpCaZlAD1GNMA9gziwE0oIZ"
      vercelToken: $(TOKEN_VERCEL)
      production: true